// File generated by github.com/ungerik/pkgreflect
package main

import "reflect"

var Types = map[string]reflect.Type{
	"Cat": reflect.TypeOf((*Cat)(nil)).Elem(),
	"Dog": reflect.TypeOf((*Dog)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
	"Bark": reflect.ValueOf(Bark),
}

var Variables = map[string]reflect.Value{
}

var Consts = map[string]reflect.Value{
}

var Interfaces = map[string]reflect.Value{
}

